# Formatting query output
use dml;
select * from salesman;
select * from orders;
select * from customer;
#1. From the following table, write a  SQL query to select all the salespeople. Return salesman_id, name, city, commission with the percent sign (%).
select salesman_id, name,city,round(commission * 100,0) as "commission%",'%' from salesman;

#2. From the following table, write a  SQL query to find the number of orders booked for each day. Return the result in a format like "For 2001-10-10 there are 15 orders".". 
select concat('For ',ord_date, ' there are ',count(ord_no), ' orders') as 'Orders on each day' from orders
group by ord_date
order by count(ord_no);

#3. From the following table, write a  SQL query to find all the orders. Sort the result-set in ascending order by ord_no. Return all fields.  
select * from orders 
order by ord_no asc;

#4. From the following table, write a  SQL query to find all the orders. Sort the result-set in descending order by ord_date. Return all fields. 
select * from orders 
order by ord_date desc;

#5. From the following table, write a  SQL query to find all the orders. Sort the result-set in descending order by ord_date and purch_amt. Return all fields.
select  *from orders 
order by ord_date , purch_amt desc;

# 6. From the following table, write a  SQL query to find all the customers. Sort the result-set by customer_id. Return cust_name, city, grade. 
select cust_name,city,grade from customer
order by customer_id; 

# 7. From the following table, write a  SQL query that calculates the maximum purchase amount generated by each salesperson for each order date. 
#Sort the result-set by salesperson id and order date in ascending order. 
#Return salesperson id, order date and maximum purchase amount. 

select salesman_id, ord_date, max(purch_amt)
from orders
group by salesman_id, ord_date
order by salesman_id,ord_date  asc;

# 8. From the following table, write a  SQL query to find all the customers. Sort the result-set in descending order on 3rd field. Return customer name, city and grade.  
select cust_name,city,grade from customer 
order by grade desc;

# or
select cust_name,city,grade from customer 
order by 3 desc; # when you 3 means 3rd field in select

# 9. From the following table, write a  SQL query that counts the unique orders and the highest purchase amount for each customer. 
#Sort the result-set in descending order on 2nd field. Return customer ID, number of distinct orders and highest purchase amount by each customer. 
select customer_id,count(distinct ord_no),max(purch_amt) from orders
group by customer_id
 order by 2 desc;
 
# 10. From the following table, write a  SQL query to calculate the summation of purchase amount, total commission (15% for all salespeople) by each order date. 
#Sort the result-set on order date. Return order date, summation of purchase amount and commission.

select ord_date, round(sum(purch_amt),1), round((sum(purch_amt) * .15),1) as 'comission_15%' from orders
group by ord_date
order by ord_date;